### PR TITLE
fix normalizing bill id

### PR DESCRIPTION
**Pull request by crdunwel**

### CODE REVIEW

**Comment by boblannon** [comment]
@JoshData did this look okay to you?

**Comment by JoshData** [comment]
Yep. You guys have perms to merge so I'll leave that to you. 🐢

**Comment by boblannon** [comment]
screenshot from 2015-09-15 16 32 33

**Comment by JoshData** [comment]
You should have an invite from yesterday. And I thought I saw @crdunwel oN the list. In the meanwhile, merging....

**Comment by JoshData** [comment]
Ha nevermind.

**Comment by crdunwel** [comment]
Yeah sorry. I can merge but prefer not to for my own PRs. Sanity check for projects involving lots of people.

**Comment by boblannon** [comment]
yeah, i was being dumb.  in my defense, though, the invitation to join didn't show up as a notification. i only saw it when i went to the unitedstates org's main page.

**Pull request merged**
