### PR TITLE
removing trailing space on 'Concur in the Senate Amendment'

### PR DESCRIPTION
**Pull request by boblannon**

### CODE REVIEW

**Comment by JoshData** [comment]
Looks good. Haven't tested but seems like it makes sense. For posterity, @boblannon reported this output:

```
 {
     ...
    "bill_id": " H.R. 720",
     ...
},
```

with an initial space causing a failure to write a good bill_id.

**Comment by crdunwel** [comment]
This conditional block isn't set up right. It appears even if the string is stripped then it still needs to be normalized. I suggest the following.
```
# treat drafts and numbered bills a bit differently
if "_" in bill_number:
    draft_bill_id = draft_bill_id_for(bill_number, date, congress)
    bill['item_type'] = 'draft_bill'
    bill['draft_bill_id'] = draft_bill_id
else:
    if "Concur in the Senate Amendment to" in bill_number:
        bill['item_type'] = 'senate_amendment'
        bill_number = bill_number.replace('Concur in the Senate Amendment to ', '')
    elif "Senate Amendment to " in bill_number:
        bill['item_type'] = 'senate_amendment'
        bill_number = bill_number.replace("Senate Amendment to ", '')
    elif "Conference report to accompany" in bill_number:
        bill['item_type'] = 'conference_report'
        bill_number = bill_number.replace("Conference report to accompany ", '')
    else:
        bill['item_type'] = 'bill'
    
    bill['bill_id'] = bill_id_for(bill_number.strip(), congress)

**Comment by boblannon** [comment]
yeah, more info:  scraper was breaking on this data from upcoming

```xml
      <floor-item id="401313" add-date="2015-09-11T16:28:30.080" remove-date="" sort-order="5" publish-date="2015-09-11T16:31:51.913">
        <legis-num>Concur in the Senate Amendment to H.R. 720</legis-num>
        <floor-text>Gerardo Hernandez Airport Security Act of 2015 </floor-text>
        <files>
          <file doc-url="http://www.gpo.gov/fdsys/pkg/BILLS-114hr720eas/pdf/BILLS-114hr720eas.pdf" doc-type="PDF" add-date="2015-09-11T16:28:28.680" sort-order="1" publish-date="2015-09-11T16:31:51.913" />
        </files>
      </floor-item>
```

**Comment by boblannon** [comment]
yeah, good call, @crdunwel

**Comment by crdunwel** [comment]
I'll make separate PR

**Comment by JoshData** [comment]
Oooops I merged too soon! Sorry!

**Comment by boblannon** [comment]
although i think @JoshData suggested that sometimes the values are totally bonkers, like "H.R. ___"

**Comment by boblannon** [comment]
oh, but that would be caught by the first condition.

**Comment by crdunwel** [comment]
see https://github.com/unitedstates/congress/pull/163

**Pull request merged**
