### PR TITLE
Update beanstalkd contrib sample

### PR DESCRIPTION
**Pull request by michaelblyons**
Fix the sample for Bills. Also add Amendments and Votes.

### CODE REVIEW

**Comment by JoshData** [comment]
I don't know enough about beanstalkd to review this PR. @konklone do you remember how this works?

**Comment by michaelblyons** [comment]
It's been a while since I did the work, but my recollection is that monkey-patching for votes basically looks like bills used to. Bills processing changed heavily at some point (https://github.com/unitedstates/congress/commit/d58df048d3b932638a403b9695db7a47449c8521?) which broke the existing monkey-patch. This commit fixes bills and adds amendments with the same pattern.

**Comment by michaelblyons** [comment]
If I may ask your indulgence for a merge, it would save me a rebase and force-push every time the codebase changes. Thank you for your consideration.

**Comment by JoshData** [comment]
Ok merging....

**Comment by michaelblyons** [comment]
Thank you!

**Pull request merged**
