### PR TITLE
Add Call by States to House voting normalization

### PR DESCRIPTION
**Pull request by handlers**
In 2013, the first House vote's question [was](http://clerk.house.gov/evs/2013/roll001.xml) "Call of the House." In 2015, it [was](http://clerk.house.gov/evs/2015/roll001.xml) "Call by States."

### CODE REVIEW

**Comment by JoshData** [comment]
Line 356 doesn't do what you want it to. Not sure what that if block is about anyway.

**Comment by handlers** [comment]
Hunh, you are right — I am now scratching my head at why that conditional is in there.

The `vote-metadata/vote-totals/totals-by-candidate/candidate` XPath looks like it's [used](http://xml.house.gov/rollcall/totals-by-candidate.HTML) in the [election of the Speaker](view-source:http://clerk.house.gov/evs/2015/roll002.xml), but not in the initial quorum vote.

**Comment by martinburch** [comment]
Can this PR be merged? Is it being held for any reason? I can't tell.

**Comment by JoshData** [comment]
Looks good to merge.

**Comment by handlers** [comment]
Sorry, lost this in the shuffle. Merging.

**Pull request merged**
