### PR TITLE
Replace THOMAS bill/amdt scrapers with bulk data importer

### PR DESCRIPTION
**Pull request by JoshData**
This PR replaces the THOMAS bill and amendment scrapers with a new data transformation script that use the new official bulk legislative data at https://github.com/usgpo/bill-status. Some of the work here was @crdunwel's, ported from his branch.

This also includes #170, the fdsys scraper PR.

To use the new script, you first have to fetch the official XML:

    ./run fdsys --collections=BILLSTATUS

which scans the FDSys sitemaps for updated files since your last run. Then you can run the new data transformation script:

    ./run bills

which outputs the same JSON (and XML) as always. The bills script _also_ outputs amendments for all bills it processes. There is no longer a separate amendments script. Called without arguments, the bills script processes all official bill XML files previously fetched by the fdsys script (except files it's already processed and haven't changed). The `bill_id` command-line parameter remains.

I've carefully compared the output of this branch for the 114th Congress with the current output of our scrapers. There are a significant number of changes, but they're mostly not very important. I can list what I found if it's helpful for others.

With THOMAS shutting off next week, I want to get this merged this weekend.

@crdunwel Do you want to port your nominations work to a new PR against the branch that created this PR?

### CODE REVIEW

**Comment by JoshData** [comment]
I've been running this in production for a few days and so far so good.

**Comment by swt83** [comment]
So this hasn't been merged yet?

**Comment by JoshData** [comment]
Well, anyone have any objections before merging?

The tests are failing but.... they're mostly about things that no longer exist.

I'll merge at the end of the day today if no objection.

**Comment by swt83** [comment]
I'm testing it now and will report back.  The only thing I can anticipate being a problem is if the converted files have different fields or something that jack up my database import.

**Comment by JoshData** [comment]
It's surely better than the output of the current scraper. :)

**Comment by JoshData** [comment]
Oh, btw, there are two bills in the 114th that don't parse which are upstream data issues (reported at https://github.com/usgpo/bill-status/issues/16), and some 500 bills in the 113th that don't parse (reported at https://github.com/usgpo/bill-status/issues/17; I haven't checked if this has been fixed recently).

**Comment by swt83** [comment]
```
[s754-114] Exception:

Traceback (most recent call last):

  File "MYPATH/machine/storage/legislation/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "MYPATH/machine/storage/legislation/tasks/bills.py", line 109, in process_bill
    process_amendments(bill_id, xml_as_dict, options)

  File "MYPATH/machine/storage/legislation/tasks/bills.py", line 216, in process_amendments
    amendment_info.process_amendment(amdt, bill_id, options)

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 13, in process_amendment
    amdt = build_amendment_json_dict(amdt_data, options)

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 36, in build_amendment_json_dict
    amends_bill = amends_bill_for(amdt_dict.get('amendedBill'))  # almost always present

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 146, in amends_bill_for
    bill_id = build_bill_id(amends_bill['type'].lower(), amends_bill['number'], amends_bill['congress'])

TypeError: 'NoneType' object has no attribute '__getitem__'


[s2943-114] Exception:

Traceback (most recent call last):

  File "MYPATH/machine/storage/legislation/tasks/utils.py", line 173, in process_set
    results = fetch_func(id, options, *extra_args)

  File "MYPATH/machine/storage/legislation/tasks/bills.py", line 109, in process_bill
    process_amendments(bill_id, xml_as_dict, options)

  File "MYPATH/machine/storage/legislation/tasks/bills.py", line 216, in process_amendments
    amendment_info.process_amendment(amdt, bill_id, options)

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 13, in process_amendment
    amdt = build_amendment_json_dict(amdt_data, options)

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 36, in build_amendment_json_dict
    amends_bill = amends_bill_for(amdt_dict.get('amendedBill'))  # almost always present

  File "MYPATH/machine/storage/legislation/tasks/amendment_info.py", line 146, in amends_bill_for
    bill_id = build_bill_id(amends_bill['type'].lower(), amends_bill['number'], amends_bill['congress'])

TypeError: 'NoneType' object has no attribute '__getitem__'


Errors for 2.
Skipped 0.
Saved data for 10371.
```

**Comment by JoshData** [comment]
> Are these fatal errors, or the script just reports and keeps going?

Reports and keeps going.

> The scanner gives me crap about .DS_store files not being directories. Might add a is_dir() check or something to the code.

Submit a PR!

**Pull request merged**
